### ISSUE TITLE
Nuget availability

### ISSUE THREAD

**Issue by dotcom9** [IdentityServer/IdentityServer3.AccessTokenValidation.Integration.AspNetCore#3]
Do you plan to distribute this project on NuGet? Is there a date set for it? Incidentally, the namespace of IApplicationBuilder in ASP.NET Core RC2 has changed to from Microsoft.AspNet.Builder Microsoft.AspNetCore.Builder - I see there is a pull request already to deal with that change.

**Comment by leastprivilege** [comment]
Why do you want to run idsrv3 on core? This is not a combination we test (nor support).

Idsrv3 is designed for Katana - use idsrv4 on core (when it is ready).

**Comment by dotcom9** [comment]
We have a legacy ASP.NET 4.5 / ID3 SSO system that is integrated with WebApi 2 and earlier, pre-Core ASP.NET apps. Changing it at the moment is not an option. The Core apps that are being integrated are built on the 4.5.1 framework and are integrated using the previous release of this project and the OICD js library. Is Idsrv4-integrated client apps and APIs running against a Idsrv3 TLS a tested/supported configuration?

**Comment by leastprivilege** [comment]
if the question is if idsrv3 and 4 are compatible on the wire - the answer is yes. Both implement the same protocol.

As long as idsrv4 is not out of beta though - we can't guarantee that everything will work 100% smoothly.

**Comment by dotcom9** [comment]
Great, got it working. Thanks.
