### ISSUE TITLE
Add DelayLoadMetaData property

### ISSUE THREAD

**Issue by alain27espina** [IdentityServer/IdentityServer3.AccessTokenValidation.Integration.AspNetCore#5]
Hi,

We are using IDSvr3 and some Web APIs using the AccessTokenValidation package. That package has the DelayLoadMetaData that we can set to avoid the race condition connecting to IDSvr3's metadata endpoint. However, we have also Web APIs built in .NET Core and we are using this package but there's no DelayLoadMetaData property. Would it be possible to add it to this package? BTW, even though they are not in the same app. Is this race condition still going to happen?

Looking at the project.json, it references the original IdentityServer3.AccessToken package but using the old version (2.3.1). Updating it to the version where DelayLoadMetaData was added should solve it, right?

**Comment by leastprivilege** [comment]
Yes you can update the version. Or use the ASP.NET Core version of the access token validation middleware.

**Comment by alain27espina** [comment]
Yeah. What I meant was, we are already using the ASP.NET Core version of the access token validation middleware but is still referencing the old version (2.3.1). So this version's project.json should be updated. The non ASP.NET Core is fine, because we are referencing the latest one. Another question is, so it is still possible to have this race condition even if the Web API is not in the same app as IDSvr?

**Comment by leastprivilege** [comment]
I recommend to always use delay loading.
